version: "3.8"

services:

  apache-zookeeper-server:
    build: .
    image: apache-kafka-ubuntu:0.3
    container_name: apache-zookeeper-server
    networks:
     - ai-kafka-network
    hostname: apache-zookeeper-server
    command: ./run_start_zookeeper.sh
    ports:
    - 2182:2181
    environment:
      ZOOKEEPER_HOST: apache-zookeeper-server
      ZOOKEEPER_PORT: 2181

  apache-kafka-broker-1:
    image: apache-kafka-ubuntu:0.3
    container_name: apache-kafka-broker-1
    networks:
     - ai-kafka-network
    hostname: apache-kafka-broker-1
    command: ./run_start_server.sh
    depends_on:
      - apache-zookeeper-server
    ports:
      - 9093:9092
    environment:
      ZOOKEEPER_HOST: apache-zookeeper-server
      ZOOKEEPER_PORT: 2181
      BROKER_ID: 1

  apache-kafka-broker-2:
    image: apache-kafka-ubuntu:0.3
    container_name: apache-kafka-broker-2
    networks:
     - ai-kafka-network
    hostname: apache-kafka-broker-2
    command: ./run_start_server.sh
    depends_on:
      - apache-zookeeper-server
    ports:
      - 9094:9092
    environment:
      ZOOKEEPER_HOST: apache-zookeeper-server
      ZOOKEEPER_PORT: 2181
      BROKER_ID: 2

  apache-kafka-broker-3:
    image: apache-kafka-ubuntu:0.3
    container_name: apache-kafka-broker-3
    networks:
     - ai-kafka-network
    hostname: apache-kafka-broker-3
    command: ./run_start_server.sh
    depends_on:
      - apache-zookeeper-server
    ports:
      - 9095:9092
    environment:
      ZOOKEEPER_HOST: apache-zookeeper-server
      ZOOKEEPER_PORT: 2181
      BROKER_ID: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
     - ai-kafka-network
    hostname: kafka-ui
    depends_on:
      - apache-zookeeper-server
    ports:
      - 8880:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: kafka-schema-registry
    networks:
     - ai-kafka-network
    hostname: kafka-schema-registry
    depends_on:
      - apache-zookeeper-server
    ports:
      - 8881:8081
    environment:
      KAFKA_ZOOKEEPER_CONNECT: apache-zookeeper-server:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://apache-kafka-broker-1:9092,PLAINTEXT://apache-kafka-broker-2:9092,PLAINTEXT://apache-kafka-broker-3:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://apache-kafka-broker-1:9092,PLAINTEXT://apache-kafka-broker-2:9092,PLAINTEXT://apache-kafka-broker-3:9092
      KAFKA_BROKERCONNECT: apache-kafka-broker-1:9092,apache-kafka-broker-2:9092,apache-kafka-broker-3:9092
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: apache-kafka-broker-1:9092,apache-kafka-broker-2:9092,apache-kafka-broker-3:9092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry

networks:
 ai-kafka-network:
  name: ai-kafka-network
  external: true
